build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.18"
  amd64: "ghcr.io/home-assistant/amd64-base:3.18"
  armv7: "ghcr.io/home-assistant/armv7-base:3.18"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: CouchDB"
  org.opencontainers.image.description: "CouchDB database server for Home Assistant"
  org.opencontainers.image.source: "https://github.com/db1996/hassio-addons"
  org.opencontainers.image.licenses: "Apache License 2.0"